name: ElixiumFriendList

main: elixiumfriendlist.ElixiumFriendList

version: 1.0

api-version: 1.13.2

Author: TheInfernoGalaxy and PlusTwentyy

description: ElixiumFriendList is a plugin for Elixium.

commands:
  friendlist:
  discription: It displays the friends list.
  usage: /friend list
  permission:
  permission-message: 
  
  unfriend:
  discription: It let's you remove friends from your list.
  usage: /friend remove
  permission:
  permission-message: 
 
  friendadd: 
    discription: It let's you add a friend to your list.
    usage: /friend add
    permission:
    permission-message: 

  friend:
    description: It shows the commands for ElixiumFriendList.
    usage: /friend
    permission: 
    permission-message: 
